// Protocol Buffers - Google's data interchange format
// Copyright 2008 Google Inc.  All rights reserved.
// https://developers.google.com/protocol-buffers/
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
//     * Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above
// copyright notice, this list of conditions and the following disclaimer
// in the documentation and/or other materials provided with the
// distribution.
//     * Neither the name of Google Inc. nor the names of its
// contributors may be used to endorse or promote products derived from
// this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: pkg.sosiv.io/sosivio-ms/sosivio-engine/framework/types/empty.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A generic empty message that you can re-use to avoid defining duplicated
// empty messages in your APIs. A typical example is to use it as the request
// or the response type of an API method. For instance:
//
//	service Foo {
//	  rpc Bar(google.protobuf.Empty) returns (google.protobuf.Empty);
//	}
type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_sosiv_io_sosivio_ms_sosivio_engine_framework_types_empty_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sosiv_io_sosivio_ms_sosivio_engine_framework_types_empty_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pkg_sosiv_io_sosivio_ms_sosivio_engine_framework_types_empty_proto_rawDescGZIP(), []int{0}
}

var File_pkg_sosiv_io_sosivio_ms_sosivio_engine_framework_types_empty_proto protoreflect.FileDescriptor

var file_pkg_sosiv_io_sosivio_ms_sosivio_engine_framework_types_empty_proto_rawDesc = []byte{
	0x0a, 0x42, 0x70, 0x6b, 0x67, 0x2e, 0x73, 0x6f, 0x73, 0x69, 0x76, 0x2e, 0x69, 0x6f, 0x2f, 0x73,
	0x6f, 0x73, 0x69, 0x76, 0x69, 0x6f, 0x2d, 0x6d, 0x73, 0x2f, 0x73, 0x6f, 0x73, 0x69, 0x76, 0x69,
	0x6f, 0x2d, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2f, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x77, 0x6f,
	0x72, 0x6b, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x73, 0x6f, 0x73, 0x69, 0x76, 0x69, 0x6f, 0x2e, 0x65, 0x6e,
	0x67, 0x69, 0x6e, 0x65, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x42, 0x3e, 0x5a, 0x3c, 0x70, 0x6b, 0x67, 0x2e, 0x73, 0x6f, 0x73, 0x69, 0x76,
	0x2e, 0x69, 0x6f, 0x2f, 0x73, 0x6f, 0x73, 0x69, 0x76, 0x69, 0x6f, 0x2d, 0x6d, 0x73, 0x2f, 0x73,
	0x6f, 0x73, 0x69, 0x76, 0x69, 0x6f, 0x2d, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2f, 0x66, 0x72,
	0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x3b, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_sosiv_io_sosivio_ms_sosivio_engine_framework_types_empty_proto_rawDescOnce sync.Once
	file_pkg_sosiv_io_sosivio_ms_sosivio_engine_framework_types_empty_proto_rawDescData = file_pkg_sosiv_io_sosivio_ms_sosivio_engine_framework_types_empty_proto_rawDesc
)

func file_pkg_sosiv_io_sosivio_ms_sosivio_engine_framework_types_empty_proto_rawDescGZIP() []byte {
	file_pkg_sosiv_io_sosivio_ms_sosivio_engine_framework_types_empty_proto_rawDescOnce.Do(func() {
		file_pkg_sosiv_io_sosivio_ms_sosivio_engine_framework_types_empty_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_sosiv_io_sosivio_ms_sosivio_engine_framework_types_empty_proto_rawDescData)
	})
	return file_pkg_sosiv_io_sosivio_ms_sosivio_engine_framework_types_empty_proto_rawDescData
}

var file_pkg_sosiv_io_sosivio_ms_sosivio_engine_framework_types_empty_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_sosiv_io_sosivio_ms_sosivio_engine_framework_types_empty_proto_goTypes = []interface{}{
	(*Empty)(nil), // 0: sosivio.engine.types.Empty
}
var file_pkg_sosiv_io_sosivio_ms_sosivio_engine_framework_types_empty_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_sosiv_io_sosivio_ms_sosivio_engine_framework_types_empty_proto_init() }
func file_pkg_sosiv_io_sosivio_ms_sosivio_engine_framework_types_empty_proto_init() {
	if File_pkg_sosiv_io_sosivio_ms_sosivio_engine_framework_types_empty_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_sosiv_io_sosivio_ms_sosivio_engine_framework_types_empty_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_sosiv_io_sosivio_ms_sosivio_engine_framework_types_empty_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_sosiv_io_sosivio_ms_sosivio_engine_framework_types_empty_proto_goTypes,
		DependencyIndexes: file_pkg_sosiv_io_sosivio_ms_sosivio_engine_framework_types_empty_proto_depIdxs,
		MessageInfos:      file_pkg_sosiv_io_sosivio_ms_sosivio_engine_framework_types_empty_proto_msgTypes,
	}.Build()
	File_pkg_sosiv_io_sosivio_ms_sosivio_engine_framework_types_empty_proto = out.File
	file_pkg_sosiv_io_sosivio_ms_sosivio_engine_framework_types_empty_proto_rawDesc = nil
	file_pkg_sosiv_io_sosivio_ms_sosivio_engine_framework_types_empty_proto_goTypes = nil
	file_pkg_sosiv_io_sosivio_ms_sosivio_engine_framework_types_empty_proto_depIdxs = nil
}
